# Site settings
title: CTF Write-ups
description: >-
  I'm a noob at CTFs but figured I'd do some write-ups for fun and to 
  document my CTF journey :)
  This site contains write-ups and some personal thoughts on the CTFs in 
  which I have participated.
domain: blog.xenosf.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.xenosf.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: xenosf/jekyll-theme-purpletermx
markdown: GFM
plugins:
  - jekyll-feed
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

exclude:
  - writeup-template.md
