# This is a basic workflow to help you get started with Actions

name: Sync gh-pages with main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          # The pull request base branch. Defaults to the branch checked out in the workflow.
          base: gh-pages
          
      # Runs a set of commands using the runners shell
      - name: git add & commit files
        run: |
          git add ':!README.md' ':!.gitignore' .
          git commit -m "Added files from main branch"
          
